name: CI
on:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: '1.23.3'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: src/provisioning

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        working-directory: src/provisioning
        run: go mod download

      - name: Build Service
        working-directory: src/provisioning
        run: go build -v ./...

      - name: Run Unit Tests
        working-directory: src/provisioning
        run: go test ./...